---

- project:
    name: app-service-configurable
    project-name: app-service-configurable
    project: app-service-configurable
    mvn-settings: app-service-configurable-settings
    pre_build_script: 'make test'
    build_script: 'make build && make docker'
    stream:
        - 'master':
              branch: 'master'
              pre_build_script: !include-raw-escape: shell/install_custom_golang.sh
              build_script: 'make test && make build docker'
              go-root: '/opt/go-custom/go'
    jobs:
        - '{project-name}-{stream}-verify-go':
              status-context: '{project-name}-{stream}-verify'
        - '{project-name}-{stream}-verify-go-arm':
              status-context: '{project-name}-{stream}-verify-arm'
        - '{project-name}-{stream}-merge-go':
              post_build_script: !include-raw-escape: shell/edgexfoundry-device-virtual-go-docker-push.sh
        - '{project-name}-{stream}-merge-go-arm':
              post_build_script: !include-raw-escape: shell/edgexfoundry-device-virtual-go-docker-push.sh
        - '{project-name}-{stream}-stage-go':
              post_build_script: !include-raw-escape: shell/edgexfoundry-device-virtual-go-docker-push.sh
        - '{project-name}-{stream}-stage-go-arm':
              post_build_script: !include-raw-escape: shell/edgexfoundry-device-virtual-go-docker-push.sh
