---

- project:
    name: app-service-configurable
    project-name: app-service-configurable
    project: app-service-configurable
    mvn-settings: app-service-configurable-settings
    stream:
      - 'master':
          branch: 'master'
    jobs:
      - '{project-name}-verify-pipeline':
          status-context: '{project-name}-verify-pipeline'
      - '{project-name}-merge-pipeline'
      - '{project-name}-pipeline-webhooks'
