DOCKER_REGISTRY=nexus3.edgexfoundry.org
GIT_BASE=https://github.com/edgexfoundry/$PROJECT
GIT_CLONE_URL=git@github.com:
GIT_URL=https://github.com
JENKINS_HOSTNAME=vex-yul-edgex-jenkins-2
LOGS_SERVER=https://logs.edgexfoundry.org
NEXUS_URL=https://nexus.edgexfoundry.org
REGISTRY_PORTS=10001 10002 10003
S3_BUCKET=
SIGUL_BRIDGE_IP=199.204.45.55
SIGUL_KEY=edgex-sandbox
SILO=sandbox
