DOCKER_REGISTRY=nexus3.edgexfoundry.org
DOCKERHUB_REGISTRY=docker.io
GIT_BASE=https://github.com/edgexfoundry/$PROJECT
GIT_CLONE_URL=git@github.com:
GIT_URL=https://github.com
JENKINS_HOSTNAME=vex-yul-edgex-jenkins-1
LOGS_SERVER=https://logs.edgexfoundry.org
NEXUS_URL=https://nexus.edgexfoundry.org
REGISTRY_PORTS=10001 10002 10003 10004
S3_BUCKET=
SIGUL_BRIDGE_IP=199.204.45.55
SIGUL_KEY=edgex-release-2020
SILO=production
